services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.25
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=America/Fortaleza # Set your timezone here
      - BASE_URL=http://localhost:4096 # URL you will use to access Zerobyte
      - APP_SECRET=change_me_generate_a_random_secret # Generate your own secret with `openssl rand -hex 32`
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - /home/titan:/home # Change it to the path you want to backup
      - /media/backup1:/backup1 # Optional
      - /media/backup2:/backup2 # Optional