services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - /home/titan/audiobookshelf/config:/config
      - /home/titan/audiobookshelf/metadata:/metadata
      - /home/titan/audiobookshelf/audiobooks:/audiobooks
      - /home/titan/audiobookshelf/podcasts:/podcasts
    environment:
      - TZ=America/Fortaleza   # Set your timezone here
